export { default as About } from "./About/About.astro";
export { default as Ad } from "./Ad/Ad.astro";
export { default as Banner } from "./Banner/Banner.astro";
export { default as Contact } from "./Contact/Contact.astro";
export { default as Prices } from "./Prices/Prices.astro";
export { default as Services } from "./Services/Services.astro";
export { default as Testimonials } from "./Testimonials/Testimonials.astro";
export { default as NavBar } from "./NavBar.tsx";
export { default as Footer } from "./Footer.astro";
export { default as SectionIntro } from "./SectionIntro";
export { default as Card } from "./Card.tsx";
export { default as Wrapper } from "./Wrapper.tsx";
export { default as Gallery} from './Gallery/Gallery.astro';
